<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/16
 * Time: 10:41
 */

namespace app\component\interfaces\message\api;


use think\Controller;

class AlimsgUrl extends Controller
{
    protected $accessKeyId;
    protected $accessKeySecret;
    protected $sendUrl;
    protected $accessTokenUrl;
    protected $jsApiTicketUrl;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->accessKeyId = 'LTAIxuB7pB8nzuZE';
        $this->accessKeySecret = 'd9uaDPMPt5f3qrWJM9uBGcppUowsNq';
        $this->sendUrl = 'https://dysmsapi.aliyuncs.com/?';
        $this->accessTokenUrl = config('wxUrl.accessTokenUrl');
        $this->jsApiTicketUrl = config('wxUrl.jsApiTicketUrl');
    }
}