<?php
namespace app\admin\controller;

use app\component\logic\ManagerLogic;
use think\Controller;
use think\Db;
use think\Request;
use think\Response;

class BaseAdmin extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('manager')){
            $this->redirect('managers/login');
        }
        //判断当前访问的URL是否在用户的权限之中
        //获取当前登录用户信息
        $mgInfo = session('manager');
        $uid = $mgInfo['id'];
        $res = Db::table('managers')->alias('m')
            ->join('role r','m.role_id=r.id')
            ->where('m.id='.$uid)
            ->find();

        //根据角色拥有的权限ids获取对应的菜单列表
        $menu_ids = explode(',',$res['menu_ids']);
        $menuinfos = Db::table('menu')->where('id','in',$menu_ids)->where(['status' => ENABLE])->order('sort desc')->select();

        $have = [];
        foreach ($menuinfos as $k => $v){
            if($v['menu_url'] != '#'){
                if(strpos($v['menu_url'],'_')){
                    $v['menu_url'] = str_replace('_','',$v['menu_url']);
                }
                array_push($have,strtolower($v['menu_url']));
            }
        }
        //获取当前的访问的url
        $controller = Request::instance()->controller();
        $action = Request::instance()->action();
        $url = strtolower($controller.'/'.$action);

        //默认允许访问的url
        $allow = ['index/welcome','index/index'];


        if(!in_array($url,$allow) && !in_array($url,$have)){
//            echo "<script> window.parent.location.reload();</script>";

            return $this->error('您没有操作权限');
        }


    }




    public function _param($key, $default = '', $emptyErrMsg = '')
    {

        $value = Request::instance()->param($key, $default);

        if ($default == $value && !empty($emptyErrMsg)) {
            $this->error($emptyErrMsg);
        }

        return $value;
    }
}