<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 14:31
 */

namespace app\component\interfaces\weixin\api;


use think\Controller;

class WxUrl extends Controller
{
    protected $appid;
    protected $secret;
    protected $grantType;
    protected $accessTokenUrl;
    protected $jsApiTicketUrl;
    protected $getWXACodeUnlimitUrl;
    protected $unifiedorderUrl;
    protected $qrcodeUrl;
    protected $showqrcodeUrl;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->appid = config('wxUrl.appid');
        $this->secret = config('wxUrl.secret');
        $this->grantType = config('wxUrl.grantType');
        $this->accessTokenUrl = config('wxUrl.accessTokenUrl');
        $this->jsApiTicketUrl = config('wxUrl.jsApiTicketUrl');
        $this->getWXACodeUnlimitUrl = config('wxUrl.getWXACodeUnlimitUrl');
        $this->unifiedorderUrl = config('wxUrl.unifiedorderUrl');
        $this->qrcodeUrl = config('wxUrl.qrcodeUrl');
        $this->showqrcodeUrl = config('wxUrl.showqrcodeUrl');
    }
}