<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/21
 * Time: 19:32
 */

namespace app\component\interfaces\auth\api;


use think\Controller;

class WxAuth extends Controller
{

    public $appId ;
    public $appsecret ;
    public $redirectUri ;
    public $responseType ;
    public $scope ;
    public $state ;
    public $grantType ;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->appId = 'wxfa1eaab45bcd6ab0';
        $this->appsecret = '24a8940db49a5494c170519f40d3ffb2';
//        $this->redirectUri = 'http://qxmapi.qxmiao.com/auth_api/login';
        $this->redirectUri = 'http://h5.qxmiao.com';
//        $this->redirectUri = 'http://h5.raydonet.com';
        $this->responseType = 'code';
        $this->scope = 'snsapi_userinfo';
        $this->state = 'STATE#wechat_redirect';
        $this->grantType = 'authorization_code';

    }
}