<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/21
 * Time: 14:11
 */

namespace app\component\interfaces\xiaochengxu\api;


use think\Controller;

class SmallUrl extends Controller
{
    protected $appid;
    protected $secret;
    protected $grantType;
    protected $code2SessionUrl;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->appid = config('xiaochengxu.appid');
        $this->secret = config('xiaochengxu.secret');
        $this->grantType = config('xiaochengxu.grantType');
        $this->code2SessionUrl = config('xiaochengxu.code2SessionUrl');
    }
}