<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 14:31
 */

namespace app\component\interfaces\house\api;


use think\Controller;

class HouseUrl extends Controller
{
    protected $userName;
    protected $password;
    protected $loginUrl;
    protected $provincesUrl;
    protected $citysUrl;
    protected $areasUrl;
    protected $constructionUrl;
    protected $construtionViewInfoByIdUrl;
    protected $buildUrl;
    protected $houseUrl;
    protected $estateEvaluationUrl;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userName = config('houseUrl.UserName');
        $this->password = config('houseUrl.Password');
        $this->loginUrl = config('houseUrl.loginUrl');
        $this->provincesUrl = config('houseUrl.provincesUrl');
        $this->citysUrl = config('houseUrl.citysUrl');
        $this->areasUrl = config('houseUrl.areasUrl');
        $this->constructionUrl = config('houseUrl.constructionUrl');
        $this->construtionViewInfoByIdUrl = config('houseUrl.construtionViewInfoByIdUrl');
        $this->buildUrl = config('houseUrl.buildUrl');
        $this->houseUrl = config('houseUrl.houseUrl');
        $this->estateEvaluationUrl = config('houseUrl.estateEvaluationUrl');
    }

    public function getHeader($token)
    {
        $header = "Authorization: Basic ". $token;
        return $header;
    }

    public function getUrl($url,$params){
        foreach ($params as $k => $v){
            $url .= '/'.$v;
        }
        return $url;
    }
}