<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/10
 * Time: 14:03
 */
namespace app\component\interfaces\oss\api;
use think\Controller;

if (is_file(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
}
if (is_file(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
}

class BaseOss extends Controller
{
    protected $accessKeyId;
    protected $accessKeySecret;
    protected $endpoint;
    protected $bucket;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->accessKeyId = config('ossConfig.accessKeyId');
        $this->accessKeySecret = config('ossConfig.accessKeySecret');
        $this->endpoint = config('ossConfig.endpoint');
        $this->bucket = config('ossConfig.bucket');
    }
}