<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/21
 * Time: 19:32
 */

namespace app\component\interfaces\wxpay\api;


use think\Controller;

class WxpayUrl extends Controller
{
    protected $appId;
    protected $mchId;
    protected $unifiedorderUrl;
    protected $key;
    protected $transfersUrl;
    protected $apiUrl;
    protected $refundUrl;
    protected $queryUrl;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->appId = config('wxPay.appid');
        $this->mchId = config('wxPay.mch_id');
        $this->key = config('wxPay.key');
        $this->apiUrl = config('webUrl.apiUrl');
        $this->unifiedorderUrl = config('wxPay.unifiedorderUrl');
        $this->transfersUrl = config('wxPay.transfersUrl');
        $this->queryUrl = config('wxPay.queryUrl');
        $this->refundUrl = config('wxPay.refundUrl');
    }
}